### ISSUE TITLE
How to specify the voxel unit size using PicoGH for Rhino Plugin Development ?

### ISSUE THREAD

**Issue by abot-eng** [wilko339/PicoGH#18]
Hello Toby ! 

I'm trying to use PicoGK directly in the Rhino Interface.
My goal is to add a command in Rhino which allows to add Gyroid to a mesh from Rhino using PicoGK.
I discovered your PicoGH package where the conversion from Rhino.Geometry.Mesh to PicoGK.Mesh is now possible. Nice work ! :)

The command works but now I would like to specifiy the voxel unit size. I can't figure out how I can manage it ? 
I thought it was defined in the picogkgh.1.3.dll but not sure about it.

Thanks for your feedback.

![image](https://github.com/user-attachments/assets/ac72821a-2773-426d-935e-6fc2ec4e588f)

Antoine

**Comment by wilko339** [comment]
Hi Antoine,

Are you trying to develop your own C# component with PicoGH or do you just want a grasshopper script to add a gyroid? 

In the PicoGH tab under Settings in grasshopper there's a component to set voxel size and some other stuff. Have a look at the examples on Food4Rhino as well: https://www.food4rhino.com/en/app/picoghbeta

**Comment by abot-eng** [comment]
Thanks for your feedback,

Yes I'm trying to develop my own C# component with PicoGH.

The process is : 
- Call the 'AddGyroid" Command in the Rhino prompt
- Select a mesh in the Rhino viewport to apply Gyroid
- Set the Gyroid settings (unit size, wall thickness)
- Get the result back in the Rhino viewport.

For small gyroid unit sizes, the result doesn't print well as the voxel unit size is too big I guess.
How can I set this voxel unit size in the C# code ? 

Regards,
Antoine

**Comment by abot-eng** [comment]
Hi, 

Quick update, I've just found what I was looking for :

`PicoGK.Library.InitLibrary(fVoxelSizeMM, fMeshAdaptivity, true, meshCoarseningFactor);`

Regards,
Antoine
